### PR TITLE
refix to escape escapable chars to correctly print out JSON form in S…

### PR DESCRIPTION
**Pull request by pigate**
Some test cases:

{"test_double_quote":"hi\""}
{"test_double_quotes":"She said, \"What?\""}
{"test_backslash_escape":"inner vocab \\"}
{"test_double_backslash_escape":"\\\\"}
{"test_blackslash_double_quote":"\\\""}
{"T":{"E":"{\"field\":\"Value with \\\"escaped quotes\\\"\"}"}}
{"E":"{\"f\":\"V \\\"e\\\"\"}"}

and test case from JSONChecker.cs

	string JSON3 = 
		@"{
	""TestObject"": {
		""SomeText"": ""Blah"",
		""SomeObject"": {
			""SomeNumber"": 42,
			""SomeFloat"": 13.37,
			""SomeBool"": true,
			""SomeNull"": null
		},
		
		""SomeEmptyObject"": { },
		""SomeEmptyArray"": [ ],
		""EmbeddedObject"": ""{\""field\"":\""Value with \\\""escaped quotes\\\""\""}""
	}
}";

### CODE REVIEW

**Comment by mtschoen** [comment]
Sorry for the long delay.  I'm just looking into this now.  I'm not sure what to do here, because while I can accept that your fix parses your tests correctly, your input is invalid JSON.

You have a \" before the field name, which is not valid.  In my example, there is an embedded JSON string in a field that uses a single ".

do you see the difference?

I'm going to mark this as closed, but please feel free to comment, and continue your own fork with your fix.

**Comment by pigate** [comment]
Hi, are you talking about:
(1) {"T":{"E":"{\"field\":\"Value with \\"escaped quotes\\"\"}"}}
(2) {"E":"{\"f\":\"V \\"e\\"\"}"}
?
If so, for (1), I meant "{\"field\":\"Value with \\"escaped quotes\\"\"}" as a literal string field for field "E"
for (2) i mean "{\"f\":\"V \\"e\\"\"}" as a literal string field for "E"

They are just strings that happen to have quotes that I created from some other json object.
What I was trying to fix is the parsing of json objects that have a string field, which happen to have double quotes in them.

**Comment by mtschoen** [comment]
Hm, ok. I see what you mean.  Even still, my parser works for those two test cases, but not all of the ones you provided.  Try double-checking your data with http://jsonlint.com/.  It's not authoritative, but I would generally say that if that service says it's invalid JSON, it's invalid JSON.

One that I'm struggling with is {"test_backslash_escape":"inner vocab \"}, which JSONLint says is valid, but I contest is not.  You should have to add one more closing quote to make that correct.

As I said, please feel free to maintain your fork, but I'm worried about unintended consequences from this change, and I don't think that it is a good idea to correctly parse invalid JSON.

**Comment by pigate** [comment]
You are correct, my mistake. I had earlier manually typed the cases in a rush. Here they are fixed after checking with JSONLint:

JSON Object test cases:

[old ok cases]
{"test_double_quote":"hi\""}
{"test_double_quotes":"She said, \"What?\""}
{"test_double_backslash_escape":"\\"}

[fixed cases]
{"test_blackslash_double_quote":"\\\""}
{"test_backslash_escape":"inner vocab \""}.
{"T": {"E": "{\"field\":\"Value with \\\"escaped quotes\\\"\"}"}}
{"E": "{\"f\":\"V\\\"e\\\"\"}"} 

Here is how I've been storing the test cases (dict):

	static Dictionary<string, string> testCasesJSONRepresentation = new Dictionary<string, string>(){
		{"1", "{\"1\":\"hi\\\"\"}"},
		{"test_double_quotes", "{\"test_double_quotes\":\"she said, \\\"What?\\\"\"}"},
		{"test_backslash_escape", "{\"test_backslash_escape\":\"inner vocab \\\\\"}"},

		{"double_backslash_escape", "{\"double_backslash_escape\":\"\\\\\\\\\"}"},
		{"blackslash_double_quote", "{\"blackslash_double_quote\":\"\\\\\\\"\"}"},
		{"test_double_quote","{\"test_double_quote\":\"hi\\\"\"}"},
		{"test_double_backslash_escape","{\"test_double_backslash_escape\":\"\\\\\"}"},
		{"test_blackslash_double_quote","{\"test_blackslash_double_quote\":\"\\\\\\\"\"}"},
		{"test_backslash_escape2","{\"test_backslash_escape2\":\"inner vocab \\\"\"}"},
	};

Thanks for catch. Appreciate it.

**Comment by mtschoen** [comment]
3 out of the 4 "fixed cases" still don't validate in JSONLint.  The only one that does is 

{"test_backslash_escape":"inner vocab \""}

Which parses correctly in JSONObject.  Sorry to be such a stickler, but I think I'm still correct in leaving the code as-is.  Can you point out a specific case which passes JSONLint but is parsed incorrectly by JSONObject?

The cases caused by escaped characters can be tricky.  My method thus far has just been to be very strict with my tests, and try to be consistent with other parsers out there.

**Comment by pigate** [comment]
Sorry, here are the fixed cases. This time, I just copied it straight from JSONLint after checking them. So these cases all now pass JSONLint but were incorrectly parsed by JSONObject.

[fixed cases]
(1)
{
	"test_blackslash_double_quote": "\\\""
}
(2)
{
	"test_backslash_escape": "inner vocab \""
}
(3)
{
	"T": {
		"E": "{\"field\":\"Value with \\\"escaped quotes\\\"\"}"
	}
}
(4)
{
	"E": "{\"f\":\"V\\\"e\\\"\"}"
}

[old ok cases]
(5)
{"test_double_quote":"hi\""}
(6)
{"test_double_quotes":"She said, \"What?\""}
(7)
{"test_double_backslash_escape":"\"}

**Pull request closed without merging**
